services:
  neo4j:
    container_name: neo4j
    image: neo4j:community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
        - ../.neo4j/data:/data
        - ../.neo4j/logs:/logs
        - ../.neo4j/import:/var/lib/neo4j/import
        - ../.neo4j/plugins:/plugins
